### ISSUE TITLE
List Files and Folders by size on Disk

### ISSUE THREAD

**Issue by afzl-wtu** [menees/DiskUsage#2]
Thanks a lot for such a great Tool. It is light weight and simple. The only problem is it lists files and folder by its shown size not its actual size on disk. The downside of this is it lists all my files on onedrive folder which are not even locally stored on my PC. 
![image](https://user-images.githubusercontent.com/64379149/181687955-3945555b-b2b4-4618-8456-cfd98a8a1791.png)
You can see, Onedrive files are even not downloaded but all of its folder are shown here:
Specially "Kurulus 2"is not locally available but it is shown most weight in the app: 
![image](https://user-images.githubusercontent.com/64379149/181688129-ec2c1fb7-a6d9-4b4a-a6e2-bfb070bf5ec9.png)
# Update:
I have only 250 GB SSD but it shows size of my C drive much larger.

**Comment by menees** [comment]
In [v3.5.0](https://github.com/menees/DiskUsage/releases/tag/v3.5.0) I added support for handling compressed files and OneDrive's on-demand files, Now it reports "size on disk" instead of just the file size.
